# Generated by Django 5.2.12 on 2026-03-17 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sermon Category',
                'verbose_name_plural': 'Sermon Categories',
            },
        ),
        migrations.CreateModel(
            name='SermonSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='series_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermon_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sermon Series',
                'verbose_name_plural': 'Sermon Series',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sermon_date', models.DateTimeField()),
                ('sermon_type', models.CharField(choices=[('sunday_service', 'Sunday Service'), ('midweek', 'Midweek Service'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('special', 'Special Service'), ('youth', 'Youth Service'), ('other', 'Other')], default='sunday_service', max_length=20)),
                ('bible_references', models.TextField(help_text='Enter Bible references, separated by commas')),
                ('audio_file', models.FileField(blank=True, upload_to='sermons/audio/')),
                ('video_file', models.FileField(blank=True, upload_to='sermons/video/')),
                ('transcript', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('slides', models.FileField(blank=True, upload_to='sermons/slides/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='sermons/thumbnails/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.sermonseries')),
            ],
            options={
                'verbose_name': 'Sermon',
                'verbose_name_plural': 'Sermons',
                'ordering': ['-sermon_date'],
            },
        ),
        migrations.CreateModel(
            name='SermonBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DurationField(blank=True, help_text='Time position in the sermon', null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='sermons.sermon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sermon Bookmark',
                'verbose_name_plural': 'Sermon Bookmarks',
                'unique_together': {('sermon', 'user', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SermonCategoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='sermons.sermoncategory')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sermons.sermon')),
            ],
            options={
                'verbose_name': 'Sermon Category Tag',
                'verbose_name_plural': 'Sermon Category Tags',
                'unique_together': {('sermon', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SermonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('timestamp', models.DurationField(blank=True, help_text='Time position in the sermon', null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='sermons.sermon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sermon Note',
                'verbose_name_plural': 'Sermon Notes',
                'unique_together': {('sermon', 'user')},
            },
        ),
    ]
