# Generated by Django 5.2.12 on 2026-04-24 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='contribution_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('tithe', 'Zaka'), ('offering', 'Sadaka'), ('special', 'Mchango Maalum'), ('other', 'Mchango Mwingine')], default='other', max_length=20),
        ),
    ]
