# Generated by Django 5.2.12 on 2026-05-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_donation_recorded_for_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('tithe', 'Zaka'), ('offering', 'Sadaka'), ('special', 'Mchango Maalum'), ('other', 'Mchango')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='tithe_gift_type',
            field=models.CharField(choices=[('money', 'Fedha'), ('asset', 'Mali')], default='money', max_length=10),
        ),
    ]
