# Generated by Django 5.2.12 on 2026-03-17 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meeting_day', models.CharField(blank=True, max_length=20)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('meeting_location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_prayer_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='prayer_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prayer Group',
                'verbose_name_plural': 'Prayer Groups',
            },
        ),
        migrations.CreateModel(
            name='PrayerGroupMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('agenda', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='prayer_meetings_attended', to=settings.AUTH_USER_MODEL)),
                ('prayer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='prayers.prayergroup')),
            ],
            options={
                'verbose_name': 'Prayer Group Meeting',
                'verbose_name_plural': 'Prayer Group Meetings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('praying', 'Currently Praying'), ('answered', 'Answered'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('leadership', 'Leadership Only')], default='public', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('prayer_count', models.PositiveIntegerField(default=0)),
                ('answered_date', models.DateTimeField(blank=True, null=True)),
                ('answered_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prayer Request',
                'verbose_name_plural': 'Prayer Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('featured', 'Featured')], default='pending', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('testimony_date', models.DateField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_testimonies', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to=settings.AUTH_USER_MODEL)),
                ('related_prayer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to='prayers.prayerrequest')),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-testimony_date'],
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_text', models.TextField(blank=True)),
                ('prayed_at', models.DateTimeField(auto_now_add=True)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayed_for', to=settings.AUTH_USER_MODEL)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='prayers.prayerrequest')),
            ],
            options={
                'verbose_name': 'Prayer',
                'verbose_name_plural': 'Prayers',
                'unique_together': {('prayer_request', 'prayer')},
            },
        ),
    ]
