# Generated by Django 5.2.12 on 2026-03-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchuser',
            name='is_verified_pastor',
            field=models.BooleanField(default=False, help_text='Pastor verification status'),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='ministry_specialization',
            field=models.CharField(blank=True, choices=[('senior_pastor', 'Senior Pastor'), ('associate_pastor', 'Associate Pastor'), ('youth_pastor', 'Youth Pastor'), ('children_pastor', 'Children Pastor'), ('worship_pastor', 'Worship Pastor'), ('outreach_pastor', 'Outreach Pastor'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='ordination_church',
            field=models.CharField(blank=True, help_text='Church where ordained', max_length=200),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='ordination_date',
            field=models.DateField(blank=True, help_text='Date of ordination', null=True),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='pastor_verification_date',
            field=models.DateTimeField(blank=True, help_text='When pastor was verified', null=True),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='pastoral_license',
            field=models.CharField(blank=True, help_text='Pastoral license number', max_length=50),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='reference_email',
            field=models.EmailField(blank=True, help_text='Reference email', max_length=254),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='reference_name',
            field=models.CharField(blank=True, help_text='Reference name', max_length=100),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='reference_phone',
            field=models.CharField(blank=True, help_text='Reference phone', max_length=20),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='theology_education',
            field=models.CharField(blank=True, help_text='Theological education', max_length=200),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='years_in_ministry',
            field=models.IntegerField(blank=True, help_text='Years in ministry', null=True),
        ),
    ]
