# Generated by Django 5.2.12 on 2026-04-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_churchgroup_groupactivity_groupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchuser',
            name='role',
            field=models.CharField(choices=[('member', 'Church Member'), ('pastor', 'Pastor'), ('elder', 'Church Elder'), ('deacon', 'Deacon'), ('accountant', 'Accountant'), ('admin', 'Administrator')], default='member', max_length=20),
        ),
    ]
