# Generated by Django 5.2.12 on 2026-04-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_churchuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchuser',
            name='can_post_member_donations',
            field=models.BooleanField(default=False, help_text="Whether this accountant can enter members' donations."),
        ),
    ]
