# Generated by Django 5.2.12 on 2026-06-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_universitystudentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitystudentrecord',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ndaki'),
        ),
    ]
